# Site settings
title: NeuroSpicy Salsa
description: Extra Heat, Different Wiring, Better Seasoning, NO APOLOGIES.
keywords: neurodivergent, ADHD, autism spectrum, parenting, neurodiverse career, job market, inclusive workplace, ADHD-inattentive, neurospicy, advocacy, Fun, Real
author: Mal
logo: /img/NeuroSpice.png
favicon: /img/IconNeuro.png 
url: "https://neurospicy-salsa.github.io"
baseurl: "/neurospicy-salsa"

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
